---
title: "View_analysis"
author: "Zc223"
date: "15/06/2018"
output: html_document
---

# Function definitions, setup

```{r}
library(stringr)
library(ggplot2)
library(dplyr)
library(magrittr)
library(corrplot)
library(robust)
library(ggpubr)
library(fit.models)
library(matrixStats)
```

## Global setting

```{r global setting}
# Use these for more than 10 algorithms
colors_20 = c(
  "#1f77b4", "#aec7e8", "#ff7f0e", "#ffbb78", "#2ca02c", "#98df8a", "#d62728", "#ff9896",
  "#9467bd", "#c5b0d5", "#8c564b", "#c49c94", "#e377c2", "#f7b6d2", "#7f7f7f", "#c7c7c7",
  "#bcbd22", "#dbdb8d", "#17becf", "#9edae5")

# Use these for 10 or fewer algorithms
colors_10 = c("#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#8c564b", "#e377c2", "#7f7f7f", "#bcbd22", "#17becf")

catscale10  = scale_colour_manual(values=colors_10)
catscale10_2 = scale_fill_manual(values=colors_10)

catscale20  = scale_colour_manual(values=colors_20)
catscale20_2 = scale_fill_manual(values=colors_20)

true_name = character()
false_name = character()

# value_set = c("1.0", "0.95", "0.9", "0.8", "0.7", "0.6")
for (i in 1: 4) {
  for (j in 1: 4) {
    for (k in 1:4) {
      true_name = c(true_name, paste("FairGPopp*, 0-TNR=", i*0.1 + 0.5, ", 1-TNR=", 
                                     j*0.1 + 0.5, ", TPR=", 
                                     k*0.1 + 0.5, sep = ""))
      false_name = c(false_name, paste("FairGPopp, 0-TNR=", i*0.1 + 0.5, ", 1-TNR=", 
                                       j*0.1 + 0.5, ", TPR=", 
                                       k*0.1 + 0.5, sep = ""))
    }
  }
}
algos_full = c(true_name, false_name)

```

## Function

```{r function for plot}
create_sensitivity_summary = function(df, x_var, y_var, view) {
  quo_x_var = enquo(x_var)
  quo_y_var = enquo(y_var)
  names(df)[names(df)==view]="choice"
  
  sensitivity_summary = 
    df %>%
    mutate(choice=recode(choice, "FairGPopp*, 1-TNR=0.6"="1-TNR=0.6"))%>%
    mutate(choice=recode(choice, "FairGPopp*, 1-TNR=0.7"="1-TNR=0.7"))%>%
    mutate(choice=recode(choice, "FairGPopp*, 1-TNR=0.8"="1-TNR=0.8"))%>%
    mutate(choice=recode(choice, "FairGPopp*, 1-TNR=0.9"="1-TNR=0.9"))%>% 
    group_by(choice) %>% 
    summarise(x_sd=sd(!!quo_x_var), x_mean=mean(!!quo_x_var), 
              y_sd=sd(!!quo_y_var), y_mean=mean(!!quo_y_var))
  sensitivity_summary
}

basic_sensitivity_plot = function(sensitivity_summary, x_var, y_var, title) {
  ggplot(sensitivity_summary, aes(x=x_mean, y=y_mean, colour=choice)) + catscale10 + catscale10_2 +
    xlab(quo_name(enquo(x_var))) + ylab(quo_name(enquo(y_var))) + 
    theme_bw() + theme(legend.position=c(0.8,0.2), legend.justification=c(0.8,0.2), 
                       legend.text=element_text(size=18), legend.title = element_blank(),
                       axis.text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
                       plot.title = element_text(size=17, face = "bold")) + ggtitle(title)
}

plot_lines_sensitity_summary = function(basic_plot) {
  basic_plot + 
    geom_segment(aes(x=x_mean - x_sd, xend = x_mean + x_sd,
                     y=y_mean, yend = y_mean,
                     colour=choice)) + 
    geom_segment(aes(x=x_mean, xend = x_mean,
                     y=y_mean - y_sd, yend = y_mean + y_sd,
                     colour=choice))
}

plot_ellipses_sensitity_summary = function(basic_plot) {
  basic_plot + stat_ellipse(level=0.5, geom="polygon", 
                            aes(fill=choice), alpha=0.2) + stat_ellipse(level=0.5, fill=NA)
}

plot_rects_sensitivity_summary = function(basic_plot) {
  aesthetics1 = aes(xmin = x_mean - 0.5 * x_sd,   
                    xmax = x_mean + 0.5 * x_sd,
                    ymin = y_mean - 0.5 * y_sd, 
                    ymax = y_mean + 0.5 * y_sd,
                    fill=choice)
  aesthetics2 = aes(xmin = x_mean - 0.5 * x_sd,   
                    xmax = x_mean + 0.5 * x_sd,
                    ymin = y_mean - 0.5 * y_sd, 
                    ymax = y_mean + 0.5 * y_sd,
                    colour=choice)
  basic_plot +
    geom_rect(aesthetics1, alpha=0.1) +
    geom_rect(aesthetics2, fill=NA)
}

plot_sensitivity = function(df, var1, var2, view, name) {
  x_var = as.name(var1)
  y_var = as.name(var2)
  
  sensitivity_summary = create_sensitivity_summary(df, !!x_var, !!y_var, view)
  basic_plot = basic_sensitivity_plot(sensitivity_summary, !!x_var, !!y_var, name)
  # Different types of plot 
  plot_rects_sensitivity_summary(basic_plot)  
  # plot_lines_sensitity_summary(basic_plot)
  # plot_ellipses_sensitity_summary(basic_plot)
  
}

make_sensitivity_figure = function(name, var1="DIbinary", var2="accuracy", algos_plot=algos_full, view="TNR1set") {
  df = read.csv(str_c(name, "_numerical-binsensitive.csv"), check.names=FALSE) %>%
    filter(algorithm %in% algos_plot)
  plot_sensitivity(df, var1, var2, view, name)
}
```

## Users setting

```{r Users setting}
file_name = c("propublica-recidivism_race","propublica-recidivism_sex")
file_attribute = c( "race", "sex")
N_file = length(file_name)
```

## Algorithm accuracy vs fairness (group-TPRDiff) all points

```{r scatter plot for all points}
variable_1 = "TPRDiff"
add_for_1 = 1
target = "accuracy"
add_for_target = 0

# view_set = c("TPRset", "TNR0set", "TNR1set")
view_set = "TNR1set"

for (i in 1:N_file) {
  
  if(add_for_target){
    target_name = paste(file_attribute[i], "-", target, sep="")
  } else {
    target_name = target
  }
  if(add_for_1){
    var1_name = paste(file_attribute[i], "-", variable_1, sep="")
  } else {
    var1_name = variable_1
  }
  
  q = make_sensitivity_figure(file_name[i], var1=var1_name, var2=target_name)
  
  print(q)
  export_name = paste(file_name[i], "_opp_tnr1.eps", sep="")
  # ggsave(export_name, q)
}

```