---
title: "Fairness analysis"
author: "magica"
date: "08/05/2018"
output: html_document
---

# Function definitions, setup

```{r}
library(stringr)
library(ggplot2)
library(dplyr)
library(magrittr)
library(corrplot)
library(robust)
library(ggpubr)
```

We'll be showing many different charts with a large number of different attributes, so a good
categorical color scale is helpful. We're using [d3](https://d3js.org) `d3.schemeCategory10` and `d3.schemeCategory20`.

```{r}
# Use these for more than 10 algorithms
colors_20 = c(
  "#1f77b4", "#aec7e8", "#ff7f0e", "#ffbb78", "#2ca02c", "#98df8a", "#d62728", "#ff9896",
  "#9467bd", "#c5b0d5", "#8c564b", "#c49c94", "#e377c2", "#f7b6d2", "#7f7f7f", "#c7c7c7",
  "#bcbd22", "#dbdb8d", "#17becf", "#9edae5")

# Use these for 10 or fewer algorithms
colors_10 = c("#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#8c564b", "#e377c2", "#7f7f7f", "#bcbd22", "#17becf")

catscale10  = scale_colour_manual(values=colors_10)
catscale10_2 = scale_fill_manual(values=colors_10)

catscale20  = scale_colour_manual(values=colors_20)
catscale20_2 = scale_fill_manual(values=colors_20)

create_sensitivity_summary = function(df, x_var, y_var) {
  quo_x_var = enquo(x_var)
  quo_y_var = enquo(y_var)
  #x_mean_name = paste0("mean_", quo_name(quo_x_var))
  #y_mean_name = paste0("mean_", quo_name(quo_y_var))
  #x_sd_name = paste0("sd_", quo_name(quo_x_var))
  #y_sd_name = paste0("sd_", quo_name(quo_y_var))
  
  sensitivity_summary = 
    df %>% 
    group_by(algorithm) %>% 
    summarise(x_sd=sd(!!quo_x_var), x_mean=mean(!!quo_x_var), 
              y_sd=sd(!!quo_y_var), y_mean=mean(!!quo_y_var))
  sensitivity_summary
}

basic_sensitivity_plot = function(sensitivity_summary, x_var, y_var) {
  ggplot(sensitivity_summary, aes(x=x_mean, y=y_mean, colour=algorithm)) + catscale10 + catscale10_2 +
    xlab(quo_name(enquo(x_var))) + ylab(quo_name(enquo(y_var)))
}

plot_lines_sensitity_summary = function(basic_plot) {
  basic_plot + 
    geom_segment(aes(x=x_mean - x_sd, xend = x_mean + x_sd,
                     y=y_mean, yend = y_mean,
                     colour=algorithm)) + 
    geom_segment(aes(x=x_mean, xend = x_mean,
                     y=y_mean - y_sd, yend = y_mean + y_sd,
                     colour=algorithm))
}

plot_ellipses_sensitity_summary = function(basic_plot) {
  basic_plot + stat_ellipse(level=0.5, geom="polygon", aes(fill=algorithm), alpha=0.2) + stat_ellipse(level=0.5, fill=NA)
}

plot_rects_sensitivity_summary = function(basic_plot) {
  aesthetics1 = aes(xmin = x_mean - 0.5 * x_sd,   
                    xmax = x_mean + 0.5 * x_sd,
                    ymin = y_mean - 0.5 * y_sd, 
                    ymax = y_mean + 0.5 * y_sd,
                    fill=algorithm)
  aesthetics2 = aes(xmin = x_mean - 0.5 * x_sd,   
                    xmax = x_mean + 0.5 * x_sd,
                    ymin = y_mean - 0.5 * y_sd, 
                    ymax = y_mean + 0.5 * y_sd,
                    colour=algorithm)
  basic_plot +
    geom_rect(aesthetics1, alpha=0.15) +
    geom_rect(aesthetics2, fill=NA)
}

do_it_all = function(name, var1, var2, check.names=FALSE) {
  df = read.csv(str_c(name, ".csv"), check.names=check.names)
  
  x_var = as.name(var1)
  y_var = as.name(var2)
  
  sensitivity_summary = create_sensitivity_summary(df, !!x_var, !!y_var)
  
  basic_plot = basic_sensitivity_plot(sensitivity_summary, !!x_var, !!y_var) + ggtitle(name)
  
  plot_rects_sensitivity_summary(basic_plot)
}

nb_measure_comparison = function(name, measure) {
  num <- read.csv(str_c(name, "_numerical.csv"), check.names=FALSE)
  nbs <- read.csv(str_c(name, "_numerical-binsensitive.csv"), check.names=FALSE)
  
  var1 <- as.name(str_c(measure, "-numerical"))
  var2 <- as.name(str_c(measure, "-binsensitive"))
  
  df <- inner_join(num, nbs, by=c("algorithm", "run-id"), suffix = c("-numerical", "-binsensitive"))
  df$name = name
  df
  # return (df %>% select(!!var1, !!var2, "run-id", "algorithm", "name"))
}

algos_to_plot = c(
  "ZafarFairness", "Calders", "SVM", 
  "Feldman-SVM", "DecisionTree", 
  "Feldman-DecisionTree", "Kamishima","FairGP_input_True", "GP_input_True", "ZafarEqOpp", "ZafarEqOdd")

make_scatter_figure = function(name, var1="CV", var2="accuracy", display="off") {
  x_var = as.name(var1)
  y_var = as.name(var2)

  df = read.csv(str_c(name, "_numerical-binsensitive.csv"), check.names=FALSE) %>%
    filter(algorithm %in% algos_to_plot) %>%
    mutate(algorithm=recode(algorithm, ZafarFairness="Zafar")) # rename to Zafar for clarity

  # Scatterplot
  switch(display,
    off = ggplot(df, aes_q(x=x_var, y=y_var, colour=quote(algorithm))) + geom_point() +
      labs(y=var2, x=var1),
    title = ggplot(df, aes_q(x=x_var, y=y_var, colour=quote(algorithm))) + geom_point() +
      labs(y=var2, x=var1, title=name),
    captain = ggplot(df, aes_q(x=x_var, y=y_var, colour=quote(algorithm))) + geom_point() +
      labs(y=var2, x=var1, caption = str_c(name, "_numerical-binsensitive.csv")),
    all = ggplot(df, aes_q(x=x_var, y=y_var, colour=quote(algorithm))) + geom_point() +
      labs(y=var2, x=var1, title=name, caption = str_c(name, "_numerical-binsensitive.csv"))
  )
}

```

## Algorithm accuracy vs fairness (CV, DIbinary, group-TPRDiff)

```{r}

q_CV = make_scatter_figure("adult_race", var1="CV", var2="accuracy", display = "title")
q_DI = make_scatter_figure("adult_race", var1="DIbinary", var2="accuracy", display = "off")
q_diff = make_scatter_figure("adult_race", var1="race-TPRDiff", var2="accuracy", display = "captain")
q = ggarrange(q_CV, q_DI, q_diff, ncol=1, nrow=3, common.legend = TRUE, legend="right")
print(q)
ggsave("AWS-result/adult_race_fair.png", q)

q_CV = make_scatter_figure("adult_sex", var1="CV", var2="accuracy", display = "title")
q_DI = make_scatter_figure("adult_sex", var1="DIbinary", var2="accuracy", display = "off")
q_diff = make_scatter_figure("adult_sex", var1="sex-TPRDiff", var2="accuracy", display = "captain")
q = ggarrange(q_CV, q_DI, q_diff, ncol=1, nrow=3, common.legend = TRUE, legend="right")
print(q)
ggsave("AWS-result/adult_sex_fair.png", q)

q_CV = make_scatter_figure("german_age", var1="CV", var2="accuracy", display = "title")
q_DI = make_scatter_figure("german_age", var1="DIbinary", var2="accuracy", display = "off")
q_diff = make_scatter_figure("german_age", var1="age-TPRDiff", var2="accuracy", display = "captain")
q = ggarrange(q_CV, q_DI, q_diff, ncol=1, nrow=3, common.legend = TRUE, legend="right")
print(q)
ggsave("AWS-result/german_age_fair.png", q)

q_CV = make_scatter_figure("german_sex", var1="CV", var2="accuracy", display = "title")
q_DI = make_scatter_figure("german_sex", var1="DIbinary", var2="accuracy", display = "off")
q_diff = make_scatter_figure("german_sex", var1="sex-TPRDiff", var2="accuracy", display = "captain")
q = ggarrange(q_CV, q_DI, q_diff, ncol=1, nrow=3, common.legend = TRUE, legend="right")
print(q)
ggsave("AWS-result/german_sex_fair.png", q)

q_CV = make_scatter_figure("propublica-recidivism_race", var1="CV", var2="accuracy", display = "title")
q_DI = make_scatter_figure("propublica-recidivism_race", var1="DIbinary", var2="accuracy", display = "off")
q_diff = make_scatter_figure("propublica-recidivism_race", var1="race-TPRDiff", var2="accuracy", display = "captain")
q = ggarrange(q_CV, q_DI, q_diff, ncol=1, nrow=3, common.legend = TRUE, legend="right")
print(q)
ggsave("AWS-result/propublica-recidivism_race_fair.png", q)

q_CV = make_scatter_figure("propublica-recidivism_sex", var1="CV", var2="accuracy", display = "title")
q_DI = make_scatter_figure("propublica-recidivism_sex", var1="DIbinary", var2="accuracy", display = "off")
q_diff = make_scatter_figure("propublica-recidivism_sex", var1="sex-TPRDiff", var2="accuracy", display = "captain")
q = ggarrange(q_CV, q_DI, q_diff, ncol=1, nrow=3, common.legend = TRUE, legend="right")
print(q)
ggsave("AWS-result/propublica-recidivism_sex_fair.png", q)

q_CV = make_scatter_figure("propublica-violent-recidivism_race", var1="CV", var2="accuracy", display = "title")
q_DI = make_scatter_figure("propublica-violent-recidivism_race", var1="DIbinary", var2="accuracy", display = "off")
q_diff = make_scatter_figure("propublica-violent-recidivism_race", var1="race-TPRDiff", var2="accuracy", display = "captain")
q = ggarrange(q_CV, q_DI, q_diff, ncol=1, nrow=3, common.legend = TRUE, legend="right")
print(q)
ggsave("AWS-result/propublica-violent-recidivism_race_fair.png", q)

q_CV = make_scatter_figure("propublica-violent-recidivism_sex", var1="CV", var2="accuracy", display = "title")
q_DI = make_scatter_figure("propublica-violent-recidivism_sex", var1="DIbinary", var2="accuracy", display = "off")
q_diff = make_scatter_figure("propublica-violent-recidivism_sex", var1="sex-TPRDiff", var2="accuracy", display = "captain")
q = ggarrange(q_CV, q_DI, q_diff, ncol=1, nrow=3, common.legend = TRUE, legend="right")
print(q)
ggsave("AWS-result/propublica-violent-recidivism_sex_fair.png", q)

q_CV = make_scatter_figure("ricci_race", var1="CV", var2="accuracy", display = "title")
q_DI = make_scatter_figure("ricci_race", var1="DIbinary", var2="accuracy", display = "off")
q_diff = make_scatter_figure("ricci_race", var1="race-TPRDiff", var2="accuracy", display = "captain")
q = ggarrange(q_CV, q_DI, q_diff, ncol=1, nrow=3, common.legend = TRUE, legend="right")
print(q)
ggsave("AWS-result/ricci_fair.png", q)

q_CV = make_scatter_figure("two-gaussians_sensitive-attr", var1="CV", var2="accuracy", display = "title")
q_DI = make_scatter_figure("two-gaussians_sensitive-attr", var1="DIbinary", var2="accuracy", display = "off")
q_DI = make_scatter_figure("two-gaussians_sensitive-attr", var1="sensitive-attr-TPRDiff", var2="accuracy", display = "captain")
q = ggarrange(q_CV, q_DI, q_diff, ncol=1, nrow=3, common.legend = TRUE, legend="right")
print(q)
ggsave("AWS-result/two-gaussians_sensitive-attr_fair.png", q)

```

## Algorithm sensitivity

```{r}
plot_sensitivity = function(df, var1, var2) {
  x_var = as.name(var1)
  y_var = as.name(var2)

  sensitivity_summary = create_sensitivity_summary(df, !!x_var, !!y_var)
  basic_plot = basic_sensitivity_plot(sensitivity_summary, !!x_var, !!y_var)
  plot_rects_sensitivity_summary(basic_plot)
}

make_sensitivity_figure = function(name, var1="DIbinary", var2="accuracy") {
  df = read.csv(name, check.names=FALSE) %>%
    filter(algorithm %in% algos_to_plot) %>%
    mutate(algorithm=recode(algorithm, ZafarFairness="Zafar")) # rename to Zafar for clarity

  plot_sensitivity(df, var1, var2)
}

p = make_sensitivity_figure("adult_sex_numerical-binsensitive.csv", var1 = "sex-TPRDiff") +
  ggtitle("Adult dataset, sex attribute")
print(p)
ggsave("AWS-result/adult_sex_diff_sensitivity.png", p)

p = make_sensitivity_figure("adult_race_numerical-binsensitive.csv", var1 = "race-TPRDiff") +
  ggtitle("Adult dataset, race attribute")
print(p)
ggsave("AWS-result/adult_race_diff_sensitivity.png", p)

p = make_sensitivity_figure("german_age_numerical-binsensitive.csv", var1 = "age-TPRDiff") +
  ggtitle("German dataset, age attribute")
print(p)
ggsave("AWS-result/german_age_diff_sensitivity.png", p)

p = make_sensitivity_figure("german_sex_numerical-binsensitive.csv", var1 = "sex-TPRDiff") +
  ggtitle("German dataset, sex attribute")
print(p)
ggsave("AWS-result/german_sex_diff_sensitivity.png", p)

p = make_sensitivity_figure("propublica-recidivism_race_numerical-binsensitive.csv", var1 = "race-TPRDiff") +
  ggtitle("Propublica-recidivism dataset, race attribute")
print(p)
ggsave("AWS-result/propublica-recidivism_race_diff_sensitivity.png", p)

p = make_sensitivity_figure("propublica-recidivism_sex_numerical-binsensitive.csv", var1 = "sex-TPRDiff") +
  ggtitle("Propublica-recidivism dataset, sex attribute")
print(p)
ggsave("AWS-result/propublica-recidivism_sex_diff_sensitivity.png", p)

p = make_sensitivity_figure("propublica-violent-recidivism_race_numerical-binsensitive.csv", var1 = "race-TPRDiff") +
  ggtitle("Propublica-violent-recidivism dataset, race attribute")
print(p)
ggsave("AWS-result/propublica-violent-recidivism_race_diff_sensitivity.png", p)

p = make_sensitivity_figure("propublica-violent-recidivism_sex_numerical-binsensitive.csv", var1 = "sex-TPRDiff") +
  ggtitle("Propublica-violent-recidivism dataset, sex attribute")
print(p)
ggsave("AWS-result/propublica-violent-recidivism_sex_diff_sensitivity.png", p)

p = make_sensitivity_figure("ricci_race_numerical-binsensitive.csv", var1 = "race-TPRDiff") +
  ggtitle("Ricci dataset, race attribute")
print(p)
ggsave("AWS-result/ricci_race_diff_sensitivity.png", p)

p = make_sensitivity_figure("two-gaussians_sensitive-attr_numerical-binsensitive.csv", var1 = "sensitive-attr-TPRDiff") +
  ggtitle("Two-gaussians_sensitive-attr dataset, sensitive attribute")
print(p)
ggsave("AWS-result/two-gaussians_sensitive-attr_diff_sensitivity.png", p)

```

